[package]
name = "tosho"
version = "0.1.0"
edition = "2024"
description = "A unified manga source library for Rust"
license = "MIT OR Apache-2.0"
repository = "https://github.com/lumisxh/tosho"
keywords = ["manga", "scraping", "async", "library"]
categories = ["web-programming", "api-bindings"]

[lib]
name = "tosho"
crate-type = ["lib"]

[dependencies]
# Builder pattern for SearchParams
derive_builder = "0.20"

# Async runtime and traits
tokio = { version = "1.4", features = [
    "rt-multi-thread",
    "macros",
    "time",
    "fs",
    "io-util",
] }
async-trait = "0.1"
futures = "0.3"

# Parallel processing for HTML parsing
rayon = "1.11"

# HTTP client with compression support
reqwest = { version = "0.12", features = ["json", "gzip", "brotli"] }
bytes = "1.10"

# HTML parsing with CSS selectors
scraper = "0.24"

# JSON/data serialization
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"

# Error handling (using thiserror for structured errors)
thiserror = "2.0"

# Concurrency and utilities
once_cell = "1.21"    # Lazy static initialization
parking_lot = "0.12"  # High-performance mutex for rate limiting
urlencoding = "2.1.3" # URL encoding for search queries
regex = "1.10"        # Regular expressions for chapter number extraction
url = "2.4"           # URL parsing and manipulation
